# Generated by Django 6.0.2 on 2026-03-03 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='farms.farm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('farm', 'entity_type', 'entity_id', 'event_type'), name='farm_events_unique_active')],
            },
        ),
    ]
