# Generated by Django 6.0.2 on 2026-03-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('rabbits', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mating', 'Злучка'), ('kindling', 'Окрол'), ('vaccination', 'Вакцинація'), ('weaning', 'Відсадка')], max_length=20)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='farmevent',
            name='farm_events_unique_active',
        ),
        migrations.AddField(
            model_name='event',
            name='rabbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rabbits.rabbit'),
        ),
        migrations.DeleteModel(
            name='FarmEvent',
        ),
    ]
