# Generated by Django 6.0.2 on 2026-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_remove_farmevent_farm_events_unique_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='next_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
