# Generated by Django 6.0.2 on 2026-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_next_action_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
