# Generated by Django 6.0.2 on 2026-03-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_next_action_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='born_alive',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='born_dead',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
