# Generated by Django 6.0.2 on 2026-04-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_born_alive_event_born_dead'),
        ('rabbits', '0013_alter_rabbit_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rabbits.group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rabbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rabbits.rabbit'),
        ),
    ]
