# Generated by Django 6.0.4 on 2026-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_group_alter_event_rabbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('mating', 'Злучка'), ('kindling', 'Окрол'), ('vaccination', 'Вакцинація'), ('weaning', 'Відсадка'), ('split', 'Розділення за статтю')], max_length=20),
        ),
    ]
