# Generated by Django 6.0.2 on 2026-09-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('mating', 'Mating'), ('kindling', 'Kindling'), ('vaccination', 'Vaccination'), ('weaning', 'Weaning'), ('split', 'Separate by Sex')], max_length=20),
        ),
    ]
