# Generated by Django 6.0.2 on 2026-02-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='sex',
            field=models.CharField(choices=[('F', 'Самка'), ('M', 'Самець')], max_length=1),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VACCINATION', 'Вакцинація'), ('MATING', 'Парування'), ('KINDLING', 'Окрол'), ('TREATMENT', 'Лікування'), ('NOTE', 'Нотатка')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rabbits.rabbit')),
            ],
        ),
    ]
