# Generated by Django 6.0.2 on 2026-02-21 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0002_alter_rabbit_sex_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kits_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='cage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='rabbits.rabbit'),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='rabbits.rabbit'),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активний'), ('SOLD', 'Проданий'), ('CULLED', 'Вибракований')], default='ACTIVE', max_length=10),
        ),
    ]
