# Generated by Django 6.0.2 on 2026-02-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0003_event_kits_count_event_responsible_event_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Інвентарний номер'),
        ),
    ]
