# Generated by Django 6.0.2 on 2026-03-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('rabbits', '0004_rabbit_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to='farms.farm'),
        ),
    ]
