# Generated by Django 6.0.2 on 2026-03-01 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('rabbits', '0005_rabbit_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='owner',
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to='farms.farm'),
            preserve_default=False,
        ),
    ]
