# Generated by Django 6.0.2 on 2026-03-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0006_remove_rabbit_owner_alter_rabbit_farm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
