# Generated by Django 6.0.2 on 2026-03-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0007_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Вага'),
        ),
    ]
