# Generated by Django 6.0.2 on 2026-03-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0009_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cage_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbits', to='rabbits.group'),
        ),
    ]
