# Generated by Django 6.0.2 on 2026-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0010_group_cage_number_rabbit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rabbit_photos/'),
        ),
    ]
