# Generated by Django 6.0.2 on 2026-04-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0011_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rabbit_photos/'),
        ),
    ]
