# Generated by Django 6.0.2 on 2026-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0012_rabbit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='sex',
            field=models.CharField(choices=[('F', 'Самка'), ('M', 'Самець'), ('U', 'Невідомо')], max_length=1),
        ),
    ]
