# Generated by Django 6.0.4 on 2026-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0013_alter_rabbit_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='father_manual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='mother_manual',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
