# Generated by Django 6.0.2 on 2026-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0014_rabbit_father_manual_rabbit_mother_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Inventory Number'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('CULLED', 'Culled')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Weight'),
        ),
    ]
