# Generated by Django 6.0.2 on 2026-08-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0015_alter_rabbit_inventory_number_alter_rabbit_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='cage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cage'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='rabbits.rabbit', verbose_name='Father'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='father_manual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Father (manual)'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbits', to='rabbits.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='rabbits.rabbit', verbose_name='Mother'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='mother_manual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mother (manual)'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rabbit_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('CULLED', 'Culled')], default='ACTIVE', max_length=10, verbose_name='Status'),
        ),
    ]
