# Generated by Django 6.0.2 on 2026-09-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0016_alter_rabbit_birth_date_alter_rabbit_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Weight')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='rabbits.rabbit', verbose_name='Rabbit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
