# Generated by Django 6.0.2 on 2026-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0017_weightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Breed name')),
                ('conditional_class', models.CharField(choices=[('medium', 'Середній'), ('large', 'Великий'), ('decorative', 'Декоративний')], max_length=20, verbose_name='Conditional class')),
                ('first_mating_age_months', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Recommended first mating age (months)')),
                ('first_mating_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Recommended first mating weight (kg)')),
            ],
            options={
                'verbose_name': 'Rabbit breed',
                'verbose_name_plural': 'Rabbit breeds',
                'ordering': ['name'],
            },
        ),
    ]
