# Generated by Django 6.0.2 on 2026-09-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0018_rabbitbreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitbreed',
            name='conditional_class',
            field=models.CharField(choices=[('medium', 'Середній'), ('large', 'Великий'), ('decorative', 'Декоративний'), ('cross_medium', 'Крос — середній'), ('cross_large', 'Крос — великий')], max_length=20, verbose_name='Conditional class'),
        ),
    ]
