# Generated by Django 6.0.2 on 2026-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0019_alter_rabbitbreed_conditional_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='conditional_class',
            field=models.CharField(blank=True, choices=[('medium', 'Середній клас'), ('large', 'Великий клас')], max_length=20, verbose_name='Conditional class'),
        ),
    ]
