# Generated by Django 6.0.2 on 2026-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
