# Generated by Django 6.0.2 on 2026-03-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_description_farm_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Місцезнаходження'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва ферми'),
        ),
    ]
