# Generated by Django 6.0.2 on 2026-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_description_alter_farm_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
