# Generated by Django 6.0.2 on 2026-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_farm_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/', verbose_name='Фото ферми'),
        ),
    ]
