# Generated by Django 6.0.2 on 2026-09-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/', verbose_name='Farm Photo'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Farm Name'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
